In [ ]:
import torch
import evaluate
from datasets import Dataset
from torch.utils.data import DataLoader
from transformers import TrainingArguments, Trainer, XLMRobertaModel, XLMRobertaTokenizerFast, XLMRobertaForTokenClassification
from transformers import get_linear_schedule_with_warmup, EarlyStoppingCallback, AutoTokenizer, AutoModelForTokenClassification, DataCollatorForTokenClassification
from torch.optim import AdamW
from sklearn.model_selection import train_test_split
import torch.nn as nn
import pandas as pd
import numpy as np
#from sklearn.metrics import classification_report
from seqeval.metrics import f1_score, classification_report, accuracy_score, precision_score, recall_score
import random
from tqdm import tqdm
import ast
import os

In [ ]:
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

In [ ]:
!pip install torch
!pip install transformers
!pip install seqeval
!pip install evaluate

Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.6 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 87.0 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 63.6 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 45.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.3 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.3 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 9.1 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 104.6 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.52.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.31.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.4.26)
Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from seqeval) (2.0.2)
Requirement already satisfied: scikit-learn>=0.21.3 in /usr/local/lib/python3.11/dist-packages (from seqeval) (1.6.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.21.3->seqeval) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.21.3->seqeval) (1.5.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.21.3->seqeval) (3.6.0)
Building wheels for collected packages: seqeval
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16162 sha256=b7f99b9941b8e359163ecae24ce507e58fd2f1f9127dc81da8e9a534a58245d4
  Stored in directory: /root/.cache/pip/wheels/bc/92/f0/243288f899c2eacdfa8c5f9aede4c71a9bad0ee26a01dc5ead
Successfully built seqeval
Installing collected packages: seqeval
Successfully installed seqeval-1.2.2
Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.14.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.15)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.2)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.31.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.15)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (3.18.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.20.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 3.5 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.3

In [ ]:
def set_random_seed(seed):
    torch.backends.cudnn.deterministic = True
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

In [ ]:
SEED = 42
set_random_seed(SEED) # seed LOCKED !!!!!!!!!!!!

PLO sorted data

In [ ]:
df = pd.read_csv('plomatch_iob_withempty.csv')
df['translated_text'] = df['translated_text'].apply(ast.literal_eval)
df['iob'] = df['iob'].apply(ast.literal_eval)

In [ ]:
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)

In [ ]:
mismatch = train_df[train_df['translated_text'].str.len() != train_df['iob'].str.len()]
print(f'Mismatches found: {len(mismatch)}')

Mismatches found: 0

In [ ]:
train_df = train_df[train_df['translated_text'].str.len() == train_df['iob'].str.len()]
val_df = val_df[val_df['translated_text'].str.len() == val_df['iob'].str.len()]

In [ ]:
train_dataset = Dataset.from_pandas(train_df[['translated_text', 'iob']])
val_dataset = Dataset.from_pandas(val_df[['translated_text', 'iob']])

In [ ]:
tokenizer = XLMRobertaTokenizerFast.from_pretrained('xlm-roberta-base')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

In [ ]:
label_list = ['O', 'B-LOC', 'I-LOC', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG']
label_to_id = {l: i for i, l in enumerate(label_list)}
id_to_label = {i: l for l, i in label_to_id.items()}

In [ ]:
def tokenize_and_align_labels(example):
    tokenized_inputs = tokenizer(
        example['translated_text'],
        is_split_into_words=True,
        truncation=True,
        padding='max_length',
        max_length=128
    )

    labels = []
    word_ids = tokenized_inputs.word_ids()
    previous_word_idx = None
    for word_idx in word_ids:
        if word_idx is None:
            labels.append(-100)
        elif word_idx != previous_word_idx:
            labels.append(label_to_id[example['iob'][word_idx]])
        else:
            labels.append(-100)
        previous_word_idx = word_idx

    tokenized_inputs['labels'] = labels
    return tokenized_inputs

In [ ]:
train_dataset = train_dataset.map(tokenize_and_align_labels)
val_dataset = val_dataset.map(tokenize_and_align_labels)

Map:   0%|          | 0/20519 [00:00<?, ? examples/s]

Map:   0%|          | 0/5134 [00:00<?, ? examples/s]

In [ ]:
def compute_metrics(p):
    predictions, labels = p
    preds = np.argmax(predictions, axis=2)

    true_labels = []
    true_preds = []

    for pred, label in zip(preds, labels):
        temp_pred = []
        temp_label = []
        for p, l in zip(pred, label):
            if l != -100:
                temp_label.append(id_to_label[l])
                temp_pred.append(id_to_label[p])
        true_labels.append(temp_label)
        true_preds.append(temp_pred)

    report = classification_report(true_labels, true_preds, output_dict=True)

    return {
        'accuracy': accuracy_score(true_labels, true_preds),  # entity-level accuracy
        'f1': f1_score(true_labels, true_preds),
        'precision': report['macro avg']['precision'],
        'recall': report['macro avg']['recall']
    }

In [ ]:
model = XLMRobertaForTokenClassification.from_pretrained(
    'xlm-roberta-base',
    num_labels=len(label_list),
    id2label=id_to_label,
    label2id=label_to_id
)

training_args = TrainingArguments(
    output_dir='./ner-xlm-roberta',
    eval_strategy='epoch',
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir='./logs',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='f1'
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Some weights of XLMRobertaForTokenClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
<ipython-input-19-a3e8f24f4de3>:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: sol-arina (sol-arina-russian-state-university-for-the-humanities) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

TrainOutput(global_step=3849, training_loss=0.024505978839742454, metrics={'train_runtime': 2089.8587, 'train_samples_per_second': 29.455, 'train_steps_per_second': 1.842, 'total_flos': 4021342888958208.0, 'train_loss': 0.024505978839742454, 'epoch': 3.0})

In [ ]:
trainer.compute_metrics = compute_metrics
metrics = trainer.evaluate()
print(metrics)

{'eval_loss': 0.011279039084911346, 'eval_accuracy': 0.997525440960666, 'eval_f1': 0.9598342365317182, 'eval_precision': 0.9489489285819377, 'eval_recall': 0.9629928860585321, 'eval_runtime': 35.857, 'eval_samples_per_second': 143.18, 'eval_steps_per_second': 8.952, 'epoch': 3.0}

In [ ]:
def compute_metrics_noO(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = []
    true_labels = []

    for pred, label in zip(predictions, labels):
        sentence_preds = []
        sentence_labels = []

        for p_id, l_id in zip(pred, label):
            if l_id == -100:
                continue
            sentence_preds.append(id_to_label[p_id])
            sentence_labels.append(id_to_label[l_id])

        true_predictions.append(sentence_preds)
        true_labels.append(sentence_labels)

    report = classification_report(true_labels, true_predictions, output_dict=True, zero_division=0)

    results = {}
    for label, scores in report.items():
        if label == 'O' or label in ['accuracy', 'macro avg', 'weighted avg']:
            continue
        results[f'{label}_f1'] = scores['f1-score']
        results[f'{label}_precision'] = scores['precision']
        results[f'{label}_recall'] = scores['recall']

    # без 'O'
    f1_scores = [v for k, v in results.items() if k.endswith('_f1')]
    results['macro_f1_excl_O'] = np.mean(f1_scores)

    return results

In [ ]:
trainer.compute_metrics = compute_metrics_noO
metrics = trainer.evaluate()
print(metrics)

{'eval_loss': 0.011279039084911346, 'eval_LOC_f1': 0.945617402431222, 'eval_LOC_precision': 0.928391959798995, 'eval_LOC_recall': 0.9634941329856584, 'eval_ORG_f1': 0.9549738219895288, 'eval_ORG_precision': 0.9519832985386222, 'eval_ORG_recall': 0.957983193277311, 'eval_PER_f1': 0.9669861554845581, 'eval_PER_precision': 0.9664715274081959, 'eval_PER_recall': 0.9675013319126265, 'eval_micro avg_f1': 0.9598342365317182, 'eval_micro avg_precision': 0.9546607482561826, 'eval_micro avg_recall': 0.9650641025641026, 'eval_macro_f1_excl_O': 0.9568529041092567, 'eval_runtime': 37.1926, 'eval_samples_per_second': 138.038, 'eval_steps_per_second': 8.631, 'epoch': 3.0}

all predictions

In [ ]:
predictions_output = trainer.predict(val_dataset)
raw_preds = predictions_output.predictions
true_labels = predictions_output.label_ids

predicted_ids = np.argmax(raw_preds, axis=2)

In [ ]:
predictions_text = []
labels_text = []

for preds, labels in zip(predicted_ids, true_labels):
    pred_seq = []
    label_seq = []
    for p, l in zip(preds, labels):
        if l != -100:
            pred_seq.append(id_to_label[p])
            label_seq.append(id_to_label[l])
    predictions_text.append(pred_seq)
    labels_text.append(label_seq)

In [ ]:
results_df = pd.DataFrame({
    'true_labels': labels_text,
    'predicted_labels': predictions_text
})

results_df.to_csv('ner_predictionsPLOfiltered.csv', index=False) # можно на них посмотреть

In [ ]:
model.save_pretrained('ner-xlm-besksl-PLOfiltered')
tokenizer.save_pretrained('ner-xlm-besksl-PLOfiltered')

('ner-xlm-besksl-PLOfiltered/tokenizer_config.json',
 'ner-xlm-besksl-PLOfiltered/special_tokens_map.json',
 'ner-xlm-besksl-PLOfiltered/sentencepiece.bpe.model',
 'ner-xlm-besksl-PLOfiltered/added_tokens.json',
 'ner-xlm-besksl-PLOfiltered/tokenizer.json')

kmeans augmented

In [ ]:
df_k = pd.read_csv('kmeans_iob_withempty.csv')
df_k['translated_text'] = df_k['translated_text'].apply(ast.literal_eval)
df_k['iob'] = df_k['iob'].apply(ast.literal_eval)

In [ ]:
train_df, val_df = train_test_split(df_k, test_size=0.2, random_state=42)

In [ ]:
mismatch = train_df[train_df['translated_text'].str.len() != train_df['iob'].str.len()]
print(f'Mismatches found: {len(mismatch)}')

Mismatches found: 0

In [ ]:
train_df = train_df[train_df['translated_text'].str.len() == train_df['iob'].str.len()]
val_df = val_df[val_df['translated_text'].str.len() == val_df['iob'].str.len()]

In [ ]:
train_dataset = Dataset.from_pandas(train_df[['translated_text', 'iob']])
val_dataset = Dataset.from_pandas(val_df[['translated_text', 'iob']])

In [ ]:
train_dataset = train_dataset.map(tokenize_and_align_labels)
val_dataset = val_dataset.map(tokenize_and_align_labels)

Map:   0%|          | 0/9373 [00:00<?, ? examples/s]

Map:   0%|          | 0/2339 [00:00<?, ? examples/s]

In [ ]:
model = XLMRobertaForTokenClassification.from_pretrained(
    'xlm-roberta-base',
    num_labels=len(label_list),
    id2label=id_to_label,
    label2id=label_to_id
)

training_args = TrainingArguments(
    output_dir='./ner-xlm-roberta',
    eval_strategy='epoch',
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir='./logs',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='f1'
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

Some weights of XLMRobertaForTokenClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
<ipython-input-35-a3e8f24f4de3>:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

TrainOutput(global_step=1758, training_loss=0.024105435040216804, metrics={'train_runtime': 1209.3896, 'train_samples_per_second': 23.251, 'train_steps_per_second': 1.454, 'total_flos': 1836933909947136.0, 'train_loss': 0.024105435040216804, 'epoch': 3.0})

In [ ]:
trainer.compute_metrics = compute_metrics
metrics = trainer.evaluate()
print(metrics)

{'eval_loss': 0.006204061210155487, 'eval_accuracy': 0.9984987561122073, 'eval_f1': 0.9266187050359712, 'eval_precision': 0.8965852130325814, 'eval_recall': 0.9701630085996663, 'eval_runtime': 16.2, 'eval_samples_per_second': 144.383, 'eval_steps_per_second': 9.074, 'epoch': 3.0}

In [ ]:
model.save_pretrained('ner-xlm-besksl-KMEANSfiltered')
tokenizer.save_pretrained('ner-xlm-besksl-KMEANSfiltered')

('ner-xlm-besksl-KMEANSfiltered/tokenizer_config.json',
 'ner-xlm-besksl-KMEANSfiltered/special_tokens_map.json',
 'ner-xlm-besksl-KMEANSfiltered/sentencepiece.bpe.model',
 'ner-xlm-besksl-KMEANSfiltered/added_tokens.json',
 'ner-xlm-besksl-KMEANSfiltered/tokenizer.json')

In [ ]:
trainer.compute_metrics = compute_metrics_noO
metrics = trainer.evaluate()
print(metrics)

{'eval_loss': 0.006204061210155487, 'eval_LOC_f1': 0.8857142857142859, 'eval_LOC_precision': 0.8303571428571429, 'eval_LOC_recall': 0.9489795918367347, 'eval_ORG_f1': 0.9801324503311258, 'eval_ORG_precision': 0.9736842105263158, 'eval_ORG_recall': 0.9866666666666667, 'eval_PER_f1': 0.9281437125748503, 'eval_PER_precision': 0.8857142857142857, 'eval_PER_recall': 0.9748427672955975, 'eval_micro avg_f1': 0.9266187050359712, 'eval_micro avg_precision': 0.8870523415977961, 'eval_micro avg_recall': 0.9698795180722891, 'eval_macro_f1_excl_O': 0.9301522884140583, 'eval_runtime': 16.7523, 'eval_samples_per_second': 139.622, 'eval_steps_per_second': 8.775, 'epoch': 3.0}

предикты

In [ ]:
predictions_output = trainer.predict(val_dataset)
raw_preds = predictions_output.predictions
true_labels = predictions_output.label_ids

predicted_ids = np.argmax(raw_preds, axis=2)

In [ ]:
predictions_text = []
labels_text = []

for preds, labels in zip(predicted_ids, true_labels):
    pred_seq = []
    label_seq = []
    for p, l in zip(preds, labels):
        if l != -100:
            pred_seq.append(id_to_label[p])
            label_seq.append(id_to_label[l])
    predictions_text.append(pred_seq)
    labels_text.append(label_seq)

In [ ]:
results_df = pd.DataFrame({
    'true_labels': labels_text,
    'predicted_labels': predictions_text
})

results_df.to_csv('ner_predictionsKMEANSfiltered.csv', index=False) # можно на них посмотреть

DBSCAN augmented

In [ ]:
df_d = pd.read_csv('dbscan_iob_withempty.csv')
df_d['translated_text'] = df_d['translated_text'].apply(ast.literal_eval)
df_d['iob'] = df_d['iob'].apply(ast.literal_eval)

In [ ]:
train_df, val_df = train_test_split(df_d, test_size=0.2, random_state=42)

In [ ]:
mismatch = train_df[train_df['translated_text'].str.len() != train_df['iob'].str.len()]
print(f'Mismatches found: {len(mismatch)}')

Mismatches found: 0

In [ ]:
train_df = train_df[train_df['translated_text'].str.len() == train_df['iob'].str.len()]
val_df = val_df[val_df['translated_text'].str.len() == val_df['iob'].str.len()]

In [ ]:
train_dataset = Dataset.from_pandas(train_df[['translated_text', 'iob']])
val_dataset = Dataset.from_pandas(val_df[['translated_text', 'iob']])

In [ ]:
train_dataset = train_dataset.map(tokenize_and_align_labels)
val_dataset = val_dataset.map(tokenize_and_align_labels)

Map:   0%|          | 0/13185 [00:00<?, ? examples/s]

Map:   0%|          | 0/3284 [00:00<?, ? examples/s]

In [ ]:
model = XLMRobertaForTokenClassification.from_pretrained(
    'xlm-roberta-base',
    num_labels=len(label_list),
    id2label=id_to_label,
    label2id=label_to_id
)

training_args = TrainingArguments(
    output_dir='./ner-xlm-roberta',
    eval_strategy='epoch',
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir='./logs',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='f1'
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

Some weights of XLMRobertaForTokenClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
<ipython-input-56-a3e8f24f4de3>:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

TrainOutput(global_step=2475, training_loss=0.030116858337864733, metrics={'train_runtime': 1313.2943, 'train_samples_per_second': 30.119, 'train_steps_per_second': 1.885, 'total_flos': 2584015107505920.0, 'train_loss': 0.030116858337864733, 'epoch': 3.0})

In [ ]:
trainer.compute_metrics = compute_metrics
metrics = trainer.evaluate()
print(metrics)

{'eval_loss': 0.007722815033048391, 'eval_accuracy': 0.9980901159681584, 'eval_f1': 0.9560094265514533, 'eval_precision': 0.9312944425809211, 'eval_recall': 0.9720317938981031, 'eval_runtime': 22.7776, 'eval_samples_per_second': 144.177, 'eval_steps_per_second': 9.044, 'epoch': 3.0}

In [ ]:
model.save_pretrained('ner-xlm-besksl-DBSCANfiltered')
tokenizer.save_pretrained('ner-xlm-besksl-DBSCANfiltered')

('ner-xlm-besksl-DBSCANfiltered/tokenizer_config.json',
 'ner-xlm-besksl-DBSCANfiltered/special_tokens_map.json',
 'ner-xlm-besksl-DBSCANfiltered/sentencepiece.bpe.model',
 'ner-xlm-besksl-DBSCANfiltered/added_tokens.json',
 'ner-xlm-besksl-DBSCANfiltered/tokenizer.json')

In [ ]:
trainer.compute_metrics = compute_metrics_noO
metrics = trainer.evaluate()
print(metrics)

{'eval_loss': 0.007722815033048391, 'eval_LOC_f1': 0.923076923076923, 'eval_LOC_precision': 0.8888888888888888, 'eval_LOC_recall': 0.96, 'eval_ORG_f1': 0.9662447257383966, 'eval_ORG_precision': 0.9581589958158996, 'eval_ORG_recall': 0.9744680851063829, 'eval_PER_f1': 0.963917525773196, 'eval_PER_precision': 0.9468354430379747, 'eval_PER_recall': 0.9816272965879265, 'eval_micro avg_f1': 0.9560094265514533, 'eval_micro avg_precision': 0.9368745188606621, 'eval_micro avg_recall': 0.9759422614274258, 'eval_macro_f1_excl_O': 0.9523121502849922, 'eval_runtime': 23.064, 'eval_samples_per_second': 142.386, 'eval_steps_per_second': 8.932, 'epoch': 3.0}

predict

In [ ]:
predictions_output = trainer.predict(val_dataset)
raw_preds = predictions_output.predictions
true_labels = predictions_output.label_ids

predicted_ids = np.argmax(raw_preds, axis=2)

In [ ]:
predictions_text = []
labels_text = []

for preds, labels in zip(predicted_ids, true_labels):
    pred_seq = []
    label_seq = []
    for p, l in zip(preds, labels):
        if l != -100:
            pred_seq.append(id_to_label[p])
            label_seq.append(id_to_label[l])
    predictions_text.append(pred_seq)
    labels_text.append(label_seq)

In [ ]:
results_df = pd.DataFrame({
    'true_labels': labels_text,
    'predicted_labels': predictions_text
})

results_df.to_csv('ner_predictionsDBSCANfiltered.csv', index=False) # можно на них посмотреть